# Generated by Django 3.1.2 on 2021-08-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Telegaram_user',
            fields=[
                ('telegram_user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fullName', models.CharField(default=None, max_length=50, null=True)),
                ('phone', models.CharField(default=None, max_length=15, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('state', models.IntegerField(default=0, null=True)),
                ('groups', models.ManyToManyField(to='bota.Group_me')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_day', models.DateField(auto_now=True)),
                ('tasks', models.TextField(null=True)),
                ('count', models.CharField(max_length=10, null=True)),
                ('state', models.IntegerField(default=0)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bota.group_me')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bota.telegaram_user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100, null=True)),
                ('dad_telegram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fatherTelegram', to='bota.telegaram_user')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bota.group_me')),
                ('mom_telegram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='motherTelegram', to='bota.telegaram_user')),
                ('self_telegram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='studentTelegram', to='bota.telegaram_user')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_day', models.DateField(auto_now=True)),
                ('answers_fmom', models.IntegerField(default=0)),
                ('answers_fdad', models.IntegerField(default=0)),
                ('answers_fs', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bota.student')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bota.task')),
            ],
        ),
    ]
