# Generated by Django 3.1.2 on 2021-08-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
