# Generated by Django 3.1.2 on 2021-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bota', '0002_auto_20210821_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
