# Generated by Django 3.1.2 on 2021-08-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bota', '0004_auto_20210813_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dad_telegram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fatherTelegram', to='bota.telegaram_user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mom_telegram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='motherTelegram', to='bota.telegaram_user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='self_telegram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='studentTelegram', to='bota.telegaram_user'),
        ),
    ]
