# Generated by Django 3.1.2 on 2021-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bota', '0005_auto_20210822_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegaram_user',
            name='role_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
