# Generated by Django 3.1.2 on 2021-08-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bota', '0006_auto_20210813_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegaram_user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
