# Generated by Django 3.1.2 on 2021-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('telegram_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(default=None, max_length=50, null=True)),
                ('phone', models.CharField(default=None, max_length=15, null=True)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
