# Generated by Django 3.1.2 on 2021-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='telegram_user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
